fix: trace env issue

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -27,6 +27,17 @@ jobs:
         node-version: '18'
     - run: npm ci
     - run: npm run build
+    - name: Create .env.production file
+      env:
+          NEXT_PUBLIC_SITE_URL: https://myth.ryuda.me
+          NODE_ENV: production
+          NEXT_PUBLIC_UMAMI_WEBSITE_ID: ${{ secrets.UMAMI_WEBSITE_ID }}
+          NEXT_PUBLIC_UMAMI_SCRIPT_URL: ${{ secrets.UMAMI_SCRIPT_URL }}
+      run: |
+        echo "NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL" >> .env.production
+        echo "NODE_ENV=$NODE_ENV" >> .env.production
+        echo "NEXT_PUBLIC_UMAMI_WEBSITE_ID=$NEXT_PUBLIC_UMAMI_WEBSITE_ID" >> .env.production
+        echo "NEXT_PUBLIC_UMAMI_SCRIPT_URL=$NEXT_PUBLIC_UMAMI_SCRIPT_URL" >> .env.production
     - name: Build Docker Image
       run: docker build -t myth:latest .
 
@@ -44,13 +55,6 @@ jobs:
     - name: Set SSH config
       run: |
         echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config
-
-    # - name: Create .env.production file
-    #   run: |
-    #     echo "NEXT_PUBLIC_SITE_URL=https://myth.ryuda.me" >> .env.production
-    #     echo "NODE_ENV=production" >> .env.production
-    #     echo "NEXT_PUBLIC_UMAMI_WEBSITE_ID=${{ secrets.UMAMI_WEBSITE_ID }}" >> .env.production
-    #     echo "NEXT_PUBLIC_UMAMI_SCRIPT_URL=${{ secrets.UMAMI_SCRIPT_URL }}" >> .env.production
 
     - name: Create deploy script
       run: |
@@ -100,23 +104,23 @@ jobs:
       env:
         HOST: ${{ secrets.HOST }}
         DEPLOY_PATH: /opt/myth/app/myth
-        NEXT_PUBLIC_SITE_URL: https://myth.ryuda.me
-        NODE_ENV: production
-        NEXT_PUBLIC_UMAMI_WEBSITE_ID: ${{ secrets.UMAMI_WEBSITE_ID }}
-        NEXT_PUBLIC_UMAMI_SCRIPT_URL: ${{ secrets.UMAMI_SCRIPT_URL }}
+        # NEXT_PUBLIC_SITE_URL: https://myth.ryuda.me
+        # NODE_ENV: production
+        # NEXT_PUBLIC_UMAMI_WEBSITE_ID: ${{ secrets.UMAMI_WEBSITE_ID }}
+        # NEXT_PUBLIC_UMAMI_SCRIPT_URL: ${{ secrets.UMAMI_SCRIPT_URL }}
       run: |
         echo "Starting SCP transfer..."
-        echo "NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL" >> .env.production
-        echo "NODE_ENV=$NODE_ENV" >> .env.production
-        echo "NEXT_PUBLIC_UMAMI_WEBSITE_ID=$NEXT_PUBLIC_UMAMI_WEBSITE_ID" >> .env.production
-        echo "NEXT_PUBLIC_UMAMI_SCRIPT_URL=$NEXT_PUBLIC_UMAMI_SCRIPT_URL" >> .env.production
+        # echo "NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL" >> .env.production
+        # echo "NODE_ENV=$NODE_ENV" >> .env.production
+        # echo "NEXT_PUBLIC_UMAMI_WEBSITE_ID=$NEXT_PUBLIC_UMAMI_WEBSITE_ID" >> .env.production
+        # echo "NEXT_PUBLIC_UMAMI_SCRIPT_URL=$NEXT_PUBLIC_UMAMI_SCRIPT_URL" >> .env.production
 
         # echo "NEXT_PUBLIC_SITE_URL=https://myth.ryuda.me" >> .env.production
         # echo "NODE_ENV=production" >> .env.production
         # echo "NEXT_PUBLIC_UMAMI_WEBSITE_ID=${{ secrets.UMAMI_WEBSITE_ID }}" >> .env.production
         # echo "NEXT_PUBLIC_UMAMI_SCRIPT_URL=${{ secrets.UMAMI_SCRIPT_URL }}" >> .env.production
 
-        scp .env.production sp-deploy@$HOST:$DEPLOY_PATH || { echo "SCP failed"; exit 1; }
+        # scp .env.production sp-deploy@$HOST:$DEPLOY_PATH || { echo "SCP failed"; exit 1; }
         scp deploy.sh sp-deploy@$HOST:$DEPLOY_PATH || { echo "SCP failed"; exit 1; }
         echo "SCP transfer completed."
 
